#!/bin/sh

GIT_USER=$(git config user.name)
GIT_EMAIL=$(git config user.email)
COMMIT_MSG_FILE=$1
 
DIFF=$(git diff -r -p -m -M --full-index --staged | cat)

(cd "${HOOK_EXEC_PATH}" && printf "%s\n" "${DIFF}" | docker-compose run php $(HOOK_COMMAND) "--git-user=$GIT_USER" "--get-email=$GIT_EMAIL" "$COMMIT_MSG_FILE")